version: "3"
services:
  frontend:
    build:
      context: ./frontend
      target: ${TARGET}
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3005:3005"
    restart: always
    volumes:
      - ./backend/src:/usr/src/app/src
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    platform: linux/amd64
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./backend/db/lawsuits.json:/lawsuits.json
      - ./backend/db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: lawsuits_db

volumes:
  mongo-data:
  mongo-config:
